### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by KillLinux** [linuxserver/Unraid-Nvidia-Plugin#10]
Hi
When I open Unraid Nvidia, the pop-up prompts that it is updating, and then the interface output is as follows

Warning: Illegal string offset 'Key' in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 48

Warning: Illegal string offset 'Key' in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 48

Warning: Illegal string offset 'Key' in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 48

Warning: Illegal string offset 'Key' in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 48

Warning: Illegal string offset 'Key' in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 48

Warning: Invalid argument supplied for foreach() in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 70

Warning: array_multisort(): Argument #3 is expected to be an array or a sort flag in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 73

Warning: Invalid argument supplied for foreach() in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 91

Warning: Invalid argument supplied for foreach() in /usr/local/emhttp/plugins/Unraid-Nvidia/include/exec.php on line 103

I don't know where except the problem, please help me.

My English is not very good, the above content is from Google Translate, please forgive me if you offend.

**Comment by j0nnymoe** [comment]
This plugin is no longer supported.
