### ISSUE TITLE
Expose variable or folder to indicate which drivers are in use?

### ISSUE THREAD

**Issue by Aterfax** [linuxserver/Unraid-Nvidia-Plugin#3]
As far as I know, for device passthrough to work properly on docker host and docker container the driver versions installed to both need to be in sync.

So to sort that between the plugin and any docker image a folder to install the drivers from / some exposed variable might be needed?

**Comment by CHBMB** [comment]
We've got things working just fine thanks.  The plugin is merely a conduit to grab builds, there's no clockwork really in it.
