### ISSUE TITLE
New UNRAID versions: update list (even if only for the stock image list)

### ISSUE THREAD

**Issue by Ahze85283** [linuxserver/Unraid-Nvidia-Plugin#8]
![image](https://user-images.githubusercontent.com/41807751/87839210-b2bdaa00-c84e-11ea-99cd-36054d67285c.png)
![image](https://user-images.githubusercontent.com/41807751/87839272-f57f8200-c84e-11ea-9a47-4c116c134167.png)

**Comment by j0nnymoe** [comment]
As mentioned in the forum thread multiple times
 We don't need to be notified everytime a new release is posted.

**Comment by Ahze85283** [comment]
FYI 
there is only 3 post on the forum that come up when you search "unraid nvidia"
so I felt I was doing A good thing by reporting than a new version is up WITH mind you a new kernel.

if you don't want the git used to notify you that the base os is updated might mention that on the readme.md

or if I'm in error Might I have a Link to the Forum post you are referring too?

**Comment by j0nnymoe** [comment]
https://forums.unraid.net/topic/77813-plugin-linuxserverio-unraid-nvidia/
